global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: spring-actuator
    scrape_interval: 15s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'localhost:8080'

remote_write:
  - url: "<grafana-cloud-url>"
    basic_auth:
      username: "<username>"
      password: "<apikey>"
